name: Deploy Website to InfinityFree

on:
  push:
    branches:
      - main   # Change to your branch if different (like master)

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Get your repository files
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Deploy to InfinityFree via FTP
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          server-dir: /htdocs/   # Change if using a custom domain folder
